CREATE TABLE IF NOT EXISTS up_quiz_users
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	PASSWORD_HASH VARCHAR(128) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO up_quiz_users (NAME, PASSWORD_HASH) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3');

CREATE TABLE IF NOT EXISTS up_quiz_quizzes
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(256) NOT NULL,
	CODE VARCHAR(4) NOT NULL,
	USER_ID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (USER_ID)
		REFERENCES up_quiz_users(ID)
		ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS up_quiz_question_display_types
(
    ID INT NOT NULL AUTO_INCREMENT,
    VALUE VARCHAR(64),
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_quiz_question_question_types
(
	ID INT NOT NULL AUTO_INCREMENT,
	VALUE VARCHAR(64),
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS up_quiz_questions
(
    ID INT NOT NULL,
    QUIZ_ID INT NOT NULL,
    QUESTION_TEXT varchar(256),
    CODE varchar(4),
    QUESTION_TYPE_ID INT NOT NULL,
    QUESTION_DISPLAY_ID INT NOT NULL,
    OPTIONS varchar(1000),
    PRIMARY KEY(ID),
	FOREIGN KEY (QUIZ_ID)
	    REFERENCES up_quiz_quizzes(ID)
	    ON DELETE CASCADE,
    FOREIGN KEY (QUESTION_TYPE_ID)
	    REFERENCES up_quiz_question_question_types(ID)
	    ON DELETE CASCADE,
	FOREIGN KEY (QUESTION_DISPLAY_ID)
	    REFERENCES up_quiz_question_display_types(ID)
	    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS up_quiz_answers
(
	ID INT NOT NULL,
	QUESTION_ID INT NOT NULL,
	ANSWER varchar(128),
	PRIMARY KEY(ID),
	FOREIGN KEY (QUESTION_ID)
		REFERENCES up_quiz_questions(ID)
		ON DELETE CASCADE
);

