CREATE TABLE IF NOT EXISTS up_quiz_users
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	PASSWORD_HASH VARCHAR(128) NOT NULL,
	PRIMARY KEY(ID)
);

INSERT INTO up_quiz_users (NAME, PASSWORD_HASH) VALUES ('admin', '21232f297a57a5a743894a0e4a801fc3');

CREATE TABLE IF NOT EXISTS up_quiz_quizzes
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(256) NOT NULL,
	CODE VARCHAR(4) NOT NULL,
    IS_ACTIVE TINYINT(1) DEFAULT 0,
	USER_ID INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY (USER_ID)
		REFERENCES up_quiz_users(ID)
		ON DELETE CASCADE
);

INSERT INTO up_quiz_quizzes (TITLE, CODE, USER_ID) VALUES ('Default', 'ZXCV', 1);


CREATE TABLE IF NOT EXISTS up_quiz_questions
(
    ID INT NOT NULL AUTO_INCREMENT,
    QUIZ_ID INT NOT NULL,
    QUESTION_TEXT varchar(256),
    CODE varchar(4),
    QUESTION_TYPE_ID TINYINT,
    QUESTION_DISPLAY_ID TINYINT,
    OPTIONS varchar(1000),
    PRIMARY KEY(ID),
	FOREIGN KEY (QUIZ_ID)
	    REFERENCES up_quiz_quizzes(ID)
	    ON DELETE CASCADE
);

INSERT INTO up_quiz_questions VALUES (1, 1, 'Кто же нальет кофейку', '1234', 0, 0, NULL), (2, 1, 'Кто же сделает чай?', '2212', 0, 0, NULL);


CREATE TABLE IF NOT EXISTS up_quiz_answers
(
	ID INT NOT NULL AUTO_INCREMENT,
	QUESTION_ID INT NOT NULL,
	ANSWER varchar(128),
	PRIMARY KEY(ID),
	FOREIGN KEY (QUESTION_ID)
		REFERENCES up_quiz_questions(ID)
		ON DELETE CASCADE
);

